# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19UbJtDzLYpLIFZh3X9y7DumxOYy9J3uw
"""

# code for adding 2 numbers 

def add(x, y):
    return x + y